import raylib;

i32 main() {
    // Initialization
    const i32 screenWidth = 800;
    const i32 screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [text] example - font loading");

    // Define characters to draw. raylib supports UTF-8 encoding;
    // the following list is codified as UTF-8 internally.
    u8* msg = "!#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHI\nJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmn\nopqrstuvwxyz{|}~¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓ\nÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷\nøùúûüýþÿ";

    // Textures/Fonts MUST be loaded after Window initialization
    // (an OpenGL context is required).

    // BMFont (AngelCode): font data and image atlas generated by
    // an external program (resources/pixantiqua.fnt requires
    // resources/pixantiqua.png alongside it).
    Font fontBm = LoadFont("resources/pixantiqua.fnt");

    // TTF font: font data and atlas are generated directly from
    // the .ttf. Base size 32 px, up to 250 characters in the atlas.
    Font fontTtf = LoadFontEx("resources/pixantiqua.ttf", 32, null, 250);

    SetTextLineSpacing(16);   // Line spacing for multiline text

    bool useTtf = false;

    SetTargetFPS(60);

    // Main game loop
    while !WindowShouldClose() {
        // Update
        if IsKeyDown(KEY_SPACE) { useTtf = true; }
        else { useTtf = false; }

        // Draw
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawText("Hold SPACE to use TTF generated font", 20, 20, 20, LIGHTGRAY);

            if !useTtf {
                DrawTextEx(fontBm, msg, Vector2{ 20.0f, 100.0f },
                           cast(f32, fontBm.baseSize), 2.0f, MAROON);
                DrawText("Using BMFont (Angelcode) imported", 20, GetScreenHeight() - 30, 20, GRAY);
            } else {
                DrawTextEx(fontTtf, msg, Vector2{ 20.0f, 100.0f },
                           cast(f32, fontTtf.baseSize), 2.0f, LIME);
                DrawText("Using TTF font generated", 20, GetScreenHeight() - 30, 20, GRAY);
            }
        EndDrawing();
    }

    // De-Initialization
    UnloadFont(fontBm);
    UnloadFont(fontTtf);

    CloseWindow();
    return 0;
}
